/** @format */
export const IMG_CDN_URL =
	'https://res.cloudinary.com/swiggy/image/upload/fl_lossy,f_auto,q_auto,w_508,h_320,c_fill/';

export const FETCH_MENU_URL =
	'https://skyfood.onrender.com/api/menu?lat=18.5204303&lng=73.8567437&restaurantId=';
// 'https://www.swiggy.com/dapi/menu/pl?page-type=REGULAR_MENU&complete-menu=true&lat=18.5204303&lng=73.8567437&restaurantId=';
export const restaurantList = [
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '200193',
			name: 'Bebe Di Rasoi - Punjabi',
			uuid: '72a41fbe-920c-43c9-983a-ae74ff0e5df7',
			city: '6',
			area: 'Senapati Bapat Road',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'qwokyvfzdond2snolvzw',
			cuisines: [
				'North Indian',
				'Punjabi',
				'Biryani',
				'Kebabs',
				'Mughlai',
				'Desserts',
				'Beverages',
			],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 41,
			minDeliveryTime: 40,
			maxDeliveryTime: 50,
			slaString: '40-50 MINS',
			lastMileTravel: 3.799999952316284,
			slugs: {
				restaurant: 'bebe-di-rasoi-shivaji-nagar-shivaji-nagar',
				city: 'pune',
			},
			cityState: '6',
			address:
				'NICE Foods, ETERNIA Rooftop, Terrace Level, B Wing, MCCIA Trade Tower, Next to Pavilion Mall, SB Road, Pune ',
			locality: 'SB Road',
			parentId: 230548,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=5830537~p=1~eid=00000186-651f-0918-0e18-415e008b0126',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3.7 kms',
			hasSurge: false,
			sla: {
				restaurantId: '200193',
				deliveryTime: 41,
				minDeliveryTime: 40,
				maxDeliveryTime: 50,
				lastMileTravel: 3.799999952316284,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.0',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '200193',
			name: 'Bebe Di Rasoi - Punjabi',
			uuid: '72a41fbe-920c-43c9-983a-ae74ff0e5df7',
			city: '6',
			area: 'Senapati Bapat Road',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'qwokyvfzdond2snolvzw',
			cuisines: [
				'North Indian',
				'Punjabi',
				'Biryani',
				'Kebabs',
				'Mughlai',
				'Desserts',
				'Beverages',
			],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 41,
			minDeliveryTime: 40,
			maxDeliveryTime: 50,
			slaString: '40-50 MINS',
			lastMileTravel: 3.799999952316284,
			slugs: {
				restaurant: 'bebe-di-rasoi-shivaji-nagar-shivaji-nagar',
				city: 'pune',
			},
			cityState: '6',
			address:
				'NICE Foods, ETERNIA Rooftop, Terrace Level, B Wing, MCCIA Trade Tower, Next to Pavilion Mall, SB Road, Pune ',
			locality: 'SB Road',
			parentId: 230548,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=5830537~p=1~eid=00000186-651f-0918-0e18-415e008b0126',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3.7 kms',
			hasSurge: false,
			sla: {
				restaurantId: '200193',
				deliveryTime: 41,
				minDeliveryTime: 40,
				maxDeliveryTime: 50,
				lastMileTravel: 3.799999952316284,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.0',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '200193',
			name: 'Bebe Di Rasoi - Punjabi',
			uuid: '72a41fbe-920c-43c9-983a-ae74ff0e5df7',
			city: '6',
			area: 'Senapati Bapat Road',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'qwokyvfzdond2snolvzw',
			cuisines: [
				'North Indian',
				'Punjabi',
				'Biryani',
				'Kebabs',
				'Mughlai',
				'Desserts',
				'Beverages',
			],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 41,
			minDeliveryTime: 40,
			maxDeliveryTime: 50,
			slaString: '40-50 MINS',
			lastMileTravel: 3.799999952316284,
			slugs: {
				restaurant: 'bebe-di-rasoi-shivaji-nagar-shivaji-nagar',
				city: 'pune',
			},
			cityState: '6',
			address:
				'NICE Foods, ETERNIA Rooftop, Terrace Level, B Wing, MCCIA Trade Tower, Next to Pavilion Mall, SB Road, Pune ',
			locality: 'SB Road',
			parentId: 230548,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=5830537~p=1~eid=00000186-651f-0918-0e18-415e008b0126',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3.7 kms',
			hasSurge: false,
			sla: {
				restaurantId: '200193',
				deliveryTime: 41,
				minDeliveryTime: 40,
				maxDeliveryTime: 50,
				lastMileTravel: 3.799999952316284,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.0',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '200193',
			name: 'Bebe Di Rasoi - Punjabi',
			uuid: '72a41fbe-920c-43c9-983a-ae74ff0e5df7',
			city: '6',
			area: 'Senapati Bapat Road',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'qwokyvfzdond2snolvzw',
			cuisines: [
				'North Indian',
				'Punjabi',
				'Biryani',
				'Kebabs',
				'Mughlai',
				'Desserts',
				'Beverages',
			],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 41,
			minDeliveryTime: 40,
			maxDeliveryTime: 50,
			slaString: '40-50 MINS',
			lastMileTravel: 3.799999952316284,
			slugs: {
				restaurant: 'bebe-di-rasoi-shivaji-nagar-shivaji-nagar',
				city: 'pune',
			},
			cityState: '6',
			address:
				'NICE Foods, ETERNIA Rooftop, Terrace Level, B Wing, MCCIA Trade Tower, Next to Pavilion Mall, SB Road, Pune ',
			locality: 'SB Road',
			parentId: 230548,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=5830537~p=1~eid=00000186-651f-0918-0e18-415e008b0126',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3.7 kms',
			hasSurge: false,
			sla: {
				restaurantId: '200193',
				deliveryTime: 41,
				minDeliveryTime: 40,
				maxDeliveryTime: 50,
				lastMileTravel: 3.799999952316284,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.0',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '200193',
			name: 'Bebe Di Rasoi - Punjabi',
			uuid: '72a41fbe-920c-43c9-983a-ae74ff0e5df7',
			city: '6',
			area: 'Senapati Bapat Road',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'qwokyvfzdond2snolvzw',
			cuisines: [
				'North Indian',
				'Punjabi',
				'Biryani',
				'Kebabs',
				'Mughlai',
				'Desserts',
				'Beverages',
			],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 41,
			minDeliveryTime: 40,
			maxDeliveryTime: 50,
			slaString: '40-50 MINS',
			lastMileTravel: 3.799999952316284,
			slugs: {
				restaurant: 'bebe-di-rasoi-shivaji-nagar-shivaji-nagar',
				city: 'pune',
			},
			cityState: '6',
			address:
				'NICE Foods, ETERNIA Rooftop, Terrace Level, B Wing, MCCIA Trade Tower, Next to Pavilion Mall, SB Road, Pune ',
			locality: 'SB Road',
			parentId: 230548,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=5830537~p=1~eid=00000186-651f-0918-0e18-415e008b0126',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3.7 kms',
			hasSurge: false,
			sla: {
				restaurantId: '200193',
				deliveryTime: 41,
				minDeliveryTime: 40,
				maxDeliveryTime: 50,
				lastMileTravel: 3.799999952316284,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.0',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '200193',
			name: 'Bebe Di Rasoi - Punjabi',
			uuid: '72a41fbe-920c-43c9-983a-ae74ff0e5df7',
			city: '6',
			area: 'Senapati Bapat Road',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'qwokyvfzdond2snolvzw',
			cuisines: [
				'North Indian',
				'Punjabi',
				'Biryani',
				'Kebabs',
				'Mughlai',
				'Desserts',
				'Beverages',
			],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 41,
			minDeliveryTime: 40,
			maxDeliveryTime: 50,
			slaString: '40-50 MINS',
			lastMileTravel: 3.799999952316284,
			slugs: {
				restaurant: 'bebe-di-rasoi-shivaji-nagar-shivaji-nagar',
				city: 'pune',
			},
			cityState: '6',
			address:
				'NICE Foods, ETERNIA Rooftop, Terrace Level, B Wing, MCCIA Trade Tower, Next to Pavilion Mall, SB Road, Pune ',
			locality: 'SB Road',
			parentId: 230548,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=5830537~p=1~eid=00000186-651f-0918-0e18-415e008b0126',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3.7 kms',
			hasSurge: false,
			sla: {
				restaurantId: '200193',
				deliveryTime: 41,
				minDeliveryTime: 40,
				maxDeliveryTime: 50,
				lastMileTravel: 3.799999952316284,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.0',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '200193',
			name: 'Bebe Di Rasoi - Punjabi',
			uuid: '72a41fbe-920c-43c9-983a-ae74ff0e5df7',
			city: '6',
			area: 'Senapati Bapat Road',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'qwokyvfzdond2snolvzw',
			cuisines: [
				'North Indian',
				'Punjabi',
				'Biryani',
				'Kebabs',
				'Mughlai',
				'Desserts',
				'Beverages',
			],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 41,
			minDeliveryTime: 40,
			maxDeliveryTime: 50,
			slaString: '40-50 MINS',
			lastMileTravel: 3.799999952316284,
			slugs: {
				restaurant: 'bebe-di-rasoi-shivaji-nagar-shivaji-nagar',
				city: 'pune',
			},
			cityState: '6',
			address:
				'NICE Foods, ETERNIA Rooftop, Terrace Level, B Wing, MCCIA Trade Tower, Next to Pavilion Mall, SB Road, Pune ',
			locality: 'SB Road',
			parentId: 230548,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=5830537~p=1~eid=00000186-651f-0918-0e18-415e008b0126',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3.7 kms',
			hasSurge: false,
			sla: {
				restaurantId: '200193',
				deliveryTime: 41,
				minDeliveryTime: 40,
				maxDeliveryTime: 50,
				lastMileTravel: 3.799999952316284,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.0',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '200193',
			name: 'Bebe Di Rasoi - Punjabi',
			uuid: '72a41fbe-920c-43c9-983a-ae74ff0e5df7',
			city: '6',
			area: 'Senapati Bapat Road',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'qwokyvfzdond2snolvzw',
			cuisines: [
				'North Indian',
				'Punjabi',
				'Biryani',
				'Kebabs',
				'Mughlai',
				'Desserts',
				'Beverages',
			],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 41,
			minDeliveryTime: 40,
			maxDeliveryTime: 50,
			slaString: '40-50 MINS',
			lastMileTravel: 3.799999952316284,
			slugs: {
				restaurant: 'bebe-di-rasoi-shivaji-nagar-shivaji-nagar',
				city: 'pune',
			},
			cityState: '6',
			address:
				'NICE Foods, ETERNIA Rooftop, Terrace Level, B Wing, MCCIA Trade Tower, Next to Pavilion Mall, SB Road, Pune ',
			locality: 'SB Road',
			parentId: 230548,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=5830537~p=1~eid=00000186-651f-0918-0e18-415e008b0126',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3.7 kms',
			hasSurge: false,
			sla: {
				restaurantId: '200193',
				deliveryTime: 41,
				minDeliveryTime: 40,
				maxDeliveryTime: 50,
				lastMileTravel: 3.799999952316284,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.0',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '200193',
			name: 'Bebe Di Rasoi - Punjabi',
			uuid: '72a41fbe-920c-43c9-983a-ae74ff0e5df7',
			city: '6',
			area: 'Senapati Bapat Road',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'qwokyvfzdond2snolvzw',
			cuisines: [
				'North Indian',
				'Punjabi',
				'Biryani',
				'Kebabs',
				'Mughlai',
				'Desserts',
				'Beverages',
			],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 41,
			minDeliveryTime: 40,
			maxDeliveryTime: 50,
			slaString: '40-50 MINS',
			lastMileTravel: 3.799999952316284,
			slugs: {
				restaurant: 'bebe-di-rasoi-shivaji-nagar-shivaji-nagar',
				city: 'pune',
			},
			cityState: '6',
			address:
				'NICE Foods, ETERNIA Rooftop, Terrace Level, B Wing, MCCIA Trade Tower, Next to Pavilion Mall, SB Road, Pune ',
			locality: 'SB Road',
			parentId: 230548,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=5830537~p=1~eid=00000186-651f-0918-0e18-415e008b0126',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3.7 kms',
			hasSurge: false,
			sla: {
				restaurantId: '200193',
				deliveryTime: 41,
				minDeliveryTime: 40,
				maxDeliveryTime: 50,
				lastMileTravel: 3.799999952316284,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.0',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
	{
		type: 'restaurant',
		data: {
			type: 'F',
			id: '200193',
			name: 'Bebe Di Rasoi - Punjabi',
			uuid: '72a41fbe-920c-43c9-983a-ae74ff0e5df7',
			city: '6',
			area: 'Senapati Bapat Road',
			totalRatingsString: '1000+ ratings',
			cloudinaryImageId: 'qwokyvfzdond2snolvzw',
			cuisines: [
				'North Indian',
				'Punjabi',
				'Biryani',
				'Kebabs',
				'Mughlai',
				'Desserts',
				'Beverages',
			],
			tags: [],
			costForTwo: 30000,
			costForTwoString: '₹300 FOR TWO',
			deliveryTime: 41,
			minDeliveryTime: 40,
			maxDeliveryTime: 50,
			slaString: '40-50 MINS',
			lastMileTravel: 3.799999952316284,
			slugs: {
				restaurant: 'bebe-di-rasoi-shivaji-nagar-shivaji-nagar',
				city: 'pune',
			},
			cityState: '6',
			address:
				'NICE Foods, ETERNIA Rooftop, Terrace Level, B Wing, MCCIA Trade Tower, Next to Pavilion Mall, SB Road, Pune ',
			locality: 'SB Road',
			parentId: 230548,
			unserviceable: false,
			veg: false,
			select: false,
			favorite: false,
			tradeCampaignHeaders: [],
			aggregatedDiscountInfo: {
				header: '50% off',
				shortDescriptionList: [
					{
						meta: '50% off | Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			aggregatedDiscountInfoV2: {
				header: '50% OFF',
				shortDescriptionList: [
					{
						meta: 'Use WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				descriptionList: [
					{
						meta: '50% off up to ₹100 | Use code WELCOME50',
						discountType: 'Percentage',
						operationType: 'RESTAURANT',
					},
				],
				subHeader: '',
				headerType: 0,
				superFreedel: '',
			},
			ribbon: [
				{
					type: 'PROMOTED',
				},
			],
			chain: [],
			feeDetails: {
				fees: [],
				totalFees: 0,
				message: '',
				title: '',
				amount: '',
				icon: '',
			},
			availability: {
				opened: true,
				nextOpenMessage: '',
				nextCloseMessage: '',
			},
			longDistanceEnabled: 0,
			rainMode: 'NONE',
			thirdPartyAddress: false,
			thirdPartyVendor: '',
			adTrackingID: 'cid=5830537~p=1~eid=00000186-651f-0918-0e18-415e008b0126',
			badges: {
				imageBased: [],
				textBased: [],
				textExtendedBadges: [],
			},
			lastMileTravelString: '3.7 kms',
			hasSurge: false,
			sla: {
				restaurantId: '200193',
				deliveryTime: 41,
				minDeliveryTime: 40,

				maxDeliveryTime: 50,
				lastMileTravel: 3.799999952316284,
				lastMileDistance: 0,
				serviceability: 'SERVICEABLE',
				rainMode: 'NONE',
				longDistance: 'NOT_LONG_DISTANCE',
				preferentialService: false,
				iconType: 'EMPTY',
			},
			promoted: true,
			avgRating: '4.0',
			totalRatings: 1000,
			new: false,
		},
		subtype: 'basic',
	},
];
